version: '3.1'

services:

    db:
        image: mariadb:10.7
        restart: always
        environment:
            MARIADB_ROOT_PASSWORD: root
        ports:
            - 3308:3306
    adminer:
        image: adminer
        restart: always
        ports:
            - 8081:8080

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 9080:80
        environment:
            UPLOAD_LIMIT: 64M


    smtp4dev-poec:
        image: rnwood/smtp4dev:v3
        restart: always
        ports:
            # Change the number before : to the port the web interface should be accessible on
            - 9081:80
            # Change the number before : to the port the SMTP server should be accessible on
            - 9025:25